### ISSUE TITLE
Is there any way to exclude some file?

### ISSUE THREAD

**Issue by osdio** [spywhere/vscode-mark-jump#1]

**Comment by spywhere** [comment]
Sorry for a very long delay. Unfortunately, Mark Jump do not have any kind of file exclusion yet as VSCode's API does not support exclusion glob pattern. However, I really want to implement this feature into it as I myself working on a large scale project.

**Comment by spywhere** [comment]
Apparently, Mark Jump already support exclusion pattern. However, excluding multiple glob patterns require a bit more complex configurations which you can take a look [here](https://github.com/Microsoft/vscode/blob/d6c61a0e12493068d2da532fdf866eb5fc3201fb/src/vs/base/test/node/glob.test.ts).
