### ISSUE TITLE
"command markJump.* not found"

### ISSUE THREAD

**Issue by 8beeeaaat** [spywhere/vscode-mark-jump#10]
<img width="1066" alt="2017-10-07 14 24 50" src="https://user-images.githubusercontent.com/4495546/31305051-701442f2-ab6b-11e7-80db-11fb75db1a03.png">

<img width="830" alt="2017-10-07 14 32 16" src="https://user-images.githubusercontent.com/4495546/31305087-58326c4e-ab6c-11e7-96c0-95414c0fa79d.png">

I installed your plugin into VS Code v1.17.0 on macOS 10.13.1.
I couldn't execute any commands.

**Comment by spywhere** [comment]
Have you map any key binding to Mark Jump commands? The latest update just change its command to a new one.

**Comment by 8beeeaaat** [comment]
@spywhere 
Thank you for your prompt response!
It seems that I was mistaken for usage that used command palette.
