### ISSUE TITLE
100% CPU usage on code 1.19

### ISSUE THREAD

**Issue by ianp** [spywhere/vscode-mark-jump#12]
Extension goes crazy reading files and pegging the CPU at almost 100% trying to run regexes over them.

- VSCode Version: Code - Insiders 1.19.0-insider (34c44f872c177d6f9439706418f8fe49bf125d08, 2017-11-17T06:08:25.346Z)
- OS Version: Darwin x64 16.7.0
- Extension: mark-jump 0.7.2

Full details over at Microsoft/vscode#38622

**Comment by spywhere** [comment]
Mark Jump does not support multi-root folder yet, hence this behaviour is expected. While waiting for a fix, you could try set `markJump.includeFilePattern` and `markJump.excludeFilePattern` to reduce the unnecessary file search which cause the issue.

**Comment by ianp** [comment]
Cool, looking into that now. I didn't think it would matter because I'm not using a multi-root workspace, but I think that `markJump.excludeFilePattern` is still the right workaround for me.
