### ISSUE TITLE
Warning always reappear on new project

### ISSUE THREAD

**Issue by tonisives** [spywhere/vscode-mark-jump#13]
This warning keeps coming up every time I open my project. Whatever I choose from the dialog, mark jump seems to continue working as expected.

I would not prefer to see this warning every time I open my project. Would it be possible to store my choice in a preference? Is this warning correct(it doesn't matter what I choose in the dialog)?

**Comment by spywhere** [comment]
You could adjust `markJump.maximumLimit` and `markJump.strictLimit` to suit your preferences. Especially `markJump.strictLimit` in order to disable the warning totally.
