### ISSUE TITLE
Is there a way to refresh the Marks in the explorer tab?

### ISSUE THREAD

**Issue by solid-pixel** [spywhere/vscode-mark-jump#14]
Hi, thanks for this life-saving extension. I couldn't be more grateful!

Is there a way to refresh the marks in the explorer tab? After I add a new one, it won't appear and it will mess up the other ones (meaning that it will add an offset to the existing marks, therefore it takes me to the wrong line when I click on them). 
The offset thing also happens if I add/remove any lines of code to my file. The marks comments inside the file will obviously move up and down in the file as I edit the code, but the marks in the explorer tab don't know that, so they will point to the old position.

The only solution I've found so far is to reload the window, but that's a bit inconvenient as I'd have to re-launch my tasks every time.

The button in the status bar works great, although it's a bit annoying to click on it every time I need to jump to one of my 50+ marks.

Thanks for your time!

**Comment by spywhere** [comment]
That's what #9 going to be fix for. I'll let you know on that issue if there's any progress. Thanks for remind me on that. :)

**Comment by spywhere** [comment]
A new version has been published. There are a few changes that might affect the settings as Mark Jump now use testing patterns to the test file before matching the marks in the file's content, but this shouldn't be hard to configure as it just a simpler version of the match itself.

**Comment by solid-pixel** [comment]
Oh man this is amazing. Thank you so much, seems to be working perfectly now from the explorer. It's even adding the new marks nearly in real time.

Even more awesome than before, thank you!
