### ISSUE TITLE
[ENHANCEMENT] includeFilePattern/excludeFilePattern list support

### ISSUE THREAD

**Issue by GeraldNDA** [spywhere/vscode-mark-jump#15]
Currently you can only put a single parttern for includeFilePattern/excludeFilePattern, however, it'd be nice if I could specify a list similar to "files.exclude", "search.exclude" etc.

**Comment by spywhere** [comment]
Please take a look [here](https://github.com/Microsoft/vscode/blob/d6c61a0e12493068d2da532fdf866eb5fc3201fb/src/vs/base/test/node/glob.test.ts) on how to setup for multiple exclusion / inclusion lists.
