### ISSUE TITLE
Feature request: add separate icon for mark jump on the sidebar.

### ISSUE THREAD

**Issue by glennmichaelmejias** [spywhere/vscode-mark-jump#17]
Mark jump is really awesome, but can you make it more similar to Bookmark that has own icon on the left side bar? It would be very awesome. Thanks!

**Comment by spywhere** [comment]
Can you elaborate more on the details? Like what exactly do you mean has its own icon the left side bar? Is it an explorer view?

**Comment by willxiang** [comment]
![sidebar](https://raw.githubusercontent.com/willxiang/code-note/master/img/Snipaste_2019-12-06_14-15-53.jpg)

I think @glennmichaelmejias means add a `mark-jump-icon` on the  left sidebar,
user click the icon then show a mark list about current tab

**Comment by spywhere** [comment]
Ah, got it. I'll see what I can do.

**Comment by willxiang** [comment]
i have notice there are button under the bottom:
![image](https://user-images.githubusercontent.com/5283629/70610881-4b4bd600-1c3f-11ea-8f03-1e7c1c9d063e.png)

so i think we don't need to add a icon on the sidebar :)

**Comment by spywhere** [comment]
Okay, I'll close the ticket then. :)
