### ISSUE TITLE
No mark is set in project 

### ISSUE THREAD

**Issue by re-f** [spywhere/vscode-mark-jump#25]
I have 2 problems
1. Mark jump can list current file mark in side bar, but I get a No mark is set. message whenever I run the markJump.jumpToProjectMarks.  
2. Mark jump **only** list current file mark in side bar, how to list all marks in project in side bar?
I recorde all problems an GIF
![no-marks](https://user-images.githubusercontent.com/8351089/66699858-fbbf5b80-ed1c-11e9-90b0-8fdd6c8b3dff.gif)

**Comment by spywhere** [comment]
Could you make a sample repository to reproduce the issue?

**Comment by spywhere** [comment]
Closed due to inactivity
