### ISSUE TITLE
I have problems with Git (Working Tree)

### ISSUE THREAD

**Issue by felocru** [spywhere/vscode-mark-jump#3]
I have experienced some problems when wanting to see the tree git work. Just do not load.
Only I disable this extension and works great. 
Thank you for extension.

**Comment by spywhere** [comment]
Could you give more information on how the problems happens? Such as, which particular extension that Mark Jump conflict with? Which version of VSCode and Mark Jump you are currently using? What do you mean by "do not load", is it freeze and when or what action did you do to make that happen? Is the extension itself working fine without using "tree git work"? Is it just happen only when using "tree git work" or something else also?

Please describe the problem as much as possible. As these information is very viable to help fix the issue only faster but also straight to the point. Thanks for filing this anyway.

**Comment by felocru** [comment]
Mark Jump: 0.3.1
Visual Code: 1.12.2
Program in Python
when i want to see the tree git work, it takes a long time to show the current file and
modified, or simply not displayed.
In the "output" appears "git show head ...", leaving waiting a long time. Then the following outputs without problems arise:
git status -z -u
git symbolic-ref --short HEAD
git rev-parse backend
...

Similarly I noticed that when opening vscode git stays in "git remote --verbose" not showing the number of files modified in the git icon.

I can not find another indicator of the problem, I just do not see any more information.
I hope this helps a bit more.

**Comment by spywhere** [comment]
As with all information you gave, you might want to customize...

- `markJump.showProjectMarks`  to `false` to limit the search to current file only
- `markJump.showStatusItem` to `false`to stop searching the files except ask (via commands)
- `markJump.excludeFilePattern` to limit the search to exclude unnecessary files
