### ISSUE TITLE
100% CPU (core) saturation

### ISSUE THREAD

**Issue by bartosz-antosik** [spywhere/vscode-mark-jump#6]
It seems that this extension (which I like BTW) saturates 100% one core of the CPU:

![mark-jump](https://user-images.githubusercontent.com/20492548/27508358-34b4cffe-58e3-11e7-8365-5747222d2bb9.png)

I am quite positive that the 25% CPU use (which is one fourth of my processor) is related to the extension.

Could something be done about it?

**Comment by spywhere** [comment]
Yes, you might want to disable `markJump.showProjectMarks`, which run through whole project in the background, or customize `markJump.includeFilePattern`/`markJump.excludeFilePattern` to limit the search scope. Mark Jump ships with only `node_modules`ignored so it very likely to have this kind of CPU usage on different projects.

**Comment by bartosz-antosik** [comment]
Please forgive me! You are right! I have observed he phenomenon and as the load at around 25% was not going down I thought there is something wrong with the extension. It is not. I was checking this this on a project which has 270MB documents in one of the folders. On smaller projects it fades away quite fast.
