### ISSUE TITLE
Hotkey for jumping to next/previous marker

### ISSUE THREAD

**Issue by vurguuz** [spywhere/vscode-mark-jump#7]
I would like to propose adding extra functionality to your great plugin: hotkeys for moving to the next and to the previous Marker in the currently open file.

For example, given:
```
// MARK: Section one
funcOne()
funcTwo()
funcThree()
// MARK: Section two
funcFour()
funcFive()
// MARK: Section three
funcSix()
```
if the cursor is on line `funcTwo()`, then pressing the `NextMarker` hotkey would move the cursor to the `// MARK: Section two` line. Pressing it a second time would move the cursor to `// MARK: Section three`. Pressing it a third time would move the cursor to `// MARK: Section one`, etc.

The `PreviousMarker` hotkey would cycle backward.

My use case is that I have a plain text general ledger file ([beancount](http://furius.ca/beancount/)) which has sections (Markers) like `Cash`, `Stocks`, `Bonds`, `Currencies`, etc. Adding new transactions is done at the **end** of a section. So if the proposed hotkeys would be made available, to add a new transaction for e.g. buying bonds, I would select the `Bonds` section from the Command Palette toolbar, hit the `NextMarker` toolkey and add lines above it.

Also `NextTodo` and `PreviousTodo` hotkeys could be useful to others.

What do you think?

**Comment by spywhere** [comment]
That's a nice feature to add. I'll let you know once I got it published.

Note to self: Find the closest marker from the cursor point.

**Comment by spywhere** [comment]
This feature has been added to v0.6.0. Please check out README file for more information on key bindings and mark-specific commands.
