### ISSUE TITLE
List marks in explorer

### ISSUE THREAD

**Issue by wiecznyPoszukiwacz** [spywhere/vscode-mark-jump#8]
Thanks for great extension!

It would be great, if marks were listed in explorer and marked with (custom?) icon in gutter.
Examples of what I mean can be seen in "Project Manager" extension or "Bookmarks" extension.

![marks](https://user-images.githubusercontent.com/322678/30637452-a62ff3ac-9df8-11e7-86af-78c84c03f477.png)

**Comment by spywhere** [comment]
That's not new, take a look [here](https://github.com/Microsoft/vscode/issues/29109). If you don't mind the icon, I could release it not so long.

**Comment by wiecznyPoszukiwacz** [comment]
Great! I can't wait when it's released :)

**Comment by spywhere** [comment]
I'll see what I can do and let you know once I got it published.

**Comment by spywhere** [comment]
This feature has been published on v0.7.0.

**Comment by wiecznyPoszukiwacz** [comment]
Thanks a lot :)
